[tool.poetry]
name = "daak"
version = "0.1.0"
description = "Asynchronous subprocess runner"
authors = ["Sean Toner <placeoftheway@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
